export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    Topline: 'Premium Bank',
    headLine: 'Unlimited Transactions with zero fees',
    description: 'get access to our exclusive app the allows you to send unlimited transactions without getting charged any fees.',
    buttonLabel: 'Get started',
    imgStart: false,
    img: require('../../images/svg-1.svg.png'),
    alt: 'Cash',
    dark: true,
    primary: true,
    darktext: false,
};

export const homeObjTwo = {
    id: 'discover',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    Topline: 'Unlimited Access',
    headLine: 'SariSplit',
    description: 'SariSplit any bill with friends whether they have SariSariPay or not. Request, track, and send payments with ease!',
    buttonLabel: 'Learn more',
    imgStart: true,
    img: require('../../images/svg-5.png'),
    alt: 'Cash',
    dark: false,
    primary: false,
    darktext: true,
};

export const homeObjThree = {
    id: 'signup',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    Topline: 'Shop Online',
    headLine: 'Unlimited Transactions with zero fees',
    description: 'Experience the convenience of online shopping even without a credit card!',
    buttonLabel: 'Start Now',
    imgStart: false,
    img: require('../../images/svg-6.png'),
    alt: 'Paper',
    dark: false,
    primary: false,
    darktext: true,
};
